// frontend/src/pages/StatsPage.vue
<template>
  <MainLayout>
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold text-gradient">
            Analytics & Statistics
          </h1>
          <p class="text-gray-400 mt-1">
            Analisi approfondite delle performance del sistema
          </p>
        </div>
        
        <div class="flex items-center gap-3">
          <select
            v-model="timeRange"
            @change="updateStats"
            class="px-3 py-2 bg-gray-800 border border-gray-700 rounded-md text-white text-sm focus:border-green-500 focus:outline-none"
          >
            <option value="7d">Ultimi 7 giorni</option>
            <option value="30d">Ultimi 30 giorni</option>
            <option value="90d">Ultimi 90 giorni</option>
          </select>
          
          <button 
            @click="refreshStats"
            :disabled="isLoading"
            class="btn-control"
          >
            <RefreshCw :class="{ 'animate-spin': isLoading }" class="h-4 w-4" />
            Aggiorna
          </button>
          
          <button class="btn-control">
            <Download class="h-4 w-4" />
            Esporta Report
          </button>
        </div>
      </div>

      <!-- Tabs Navigation -->
      <div class="control-card p-1">
        <div class="flex items-center gap-1">
          <button
            v-for="tab in tabs"
            :key="tab.id"
            @click="activeTab = tab.id"
            class="flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all"
            :class="activeTab === tab.id
              ? 'bg-green-500 text-white'
              : 'text-gray-300 hover:bg-gray-800 hover:text-white'"
          >
            <component :is="tab.icon" class="h-4 w-4" />
            {{ tab.label }}
          </button>
        </div>
      </div>

      <!-- Overview Tab -->
      <div v-if="activeTab === 'overview'" class="space-y-6">
        <!-- Key Metrics -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <div
            v-for="(metric, index) in keyMetrics"
            :key="index"
            class="control-card p-6"
          >
            <div class="flex items-start justify-between">
              <div class="flex-1">
                <p class="text-sm text-gray-400 mb-1">{{ metric.title }}</p>
                <p class="text-2xl font-bold text-white">{{ metric.value }}</p>
                <div v-if="metric.change !== undefined" class="flex items-center gap-1 mt-2 text-sm text-green-400">
                  <TrendingUp class="h-3 w-3" />
                  <span>{{ metric.change > 0 ? '+' : '' }}{{ metric.change }}% vs scorsa settimana</span>
                </div>
              </div>
              <div class="text-gray-600">
                <component :is="metric.icon" class="h-8 w-8" />
              </div>
            </div>
          </div>
        </div>

        <!-- Performance Metrics -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div class="control-card p-6">
            <h3 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Timer class="h-5 w-5 text-green-400" />
              Tempi di Esecuzione
            </h3>
            <div class="space-y-4">
              <div class="flex items-center justify-between">
                <span class="text-gray-400">Tempo Medio</span>
                <span class="text-white font-mono">{{ formatDuration(avgExecutionTime) }}</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-gray-400">Miglioramento</span>
                <span class="text-green-400 font-medium">-15.2% vs scorsa settimana</span>
              </div>
            </div>
          </div>

          <div class="control-card p-6">
            <h3 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <PieChart class="h-5 w-5 text-green-400" />
              Distribuzione Workflow Types
            </h3>
            <div class="space-y-3">
              <div
                v-for="type in workflowTypes"
                :key="type.type"
                class="flex items-center justify-between"
              >
                <span class="text-gray-400">{{ type.type }}</span>
                <div class="flex items-center gap-2">
                  <div class="w-20 bg-gray-800 rounded-full h-2">
                    <div 
                      class="bg-green-500 h-2 rounded-full transition-all duration-500"
                      :style="{ width: `${Math.min(type.percentage, 100)}%` }"
                    />
                  </div>
                  <span class="text-white font-medium w-12 text-right">{{ type.count }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Performance Tab -->
      <div v-if="activeTab === 'performance'" class="space-y-6">
        <div class="control-card p-6">
          <h3 class="text-lg font-semibold text-white mb-4">Performance Trends</h3>
          <div class="h-64">
            <Line
              v-if="!chartsLoading"
              :data="performanceChartData"
              :options="chartOptions"
            />
            <div v-else class="flex items-center justify-center h-full">
              <Loader2 class="h-8 w-8 animate-spin text-green-400" />
            </div>
          </div>
        </div>
      </div>

      <!-- Analytics Tab -->
      <div v-if="activeTab === 'analytics'" class="space-y-6">
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <!-- Peak Hours -->
          <div class="control-card p-6">
            <h3 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Clock class="h-5 w-5 text-blue-400" />
              Ore di Picco
            </h3>
            <div class="space-y-3">
              <div
                v-for="peak in peakHours"
                :key="peak.hour"
                class="flex items-center justify-between p-3 bg-gray-800/50 rounded-lg"
              >
                <span class="text-white font-medium">{{ peak.hour }}:00 - {{ peak.hour + 1 }}:00</span>
                <div class="flex items-center gap-2">
                  <div class="w-24 bg-gray-700 rounded-full h-2">
                    <div 
                      class="bg-blue-500 h-2 rounded-full"
                      :style="{ width: `${Math.min((peak.avgExecutions / 150) * 100, 100)}%` }"
                    />
                  </div>
                  <span class="text-blue-400 font-mono">{{ peak.avgExecutions }} exec/h</span>
                </div>
              </div>
            </div>
          </div>

          <!-- System Health -->
          <div class="control-card p-6">
            <h3 class="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <Database class="h-5 w-5 text-green-400" />
              System Health
            </h3>
            <div class="space-y-4">
              <div class="flex items-center justify-between">
                <span class="text-gray-400">System Load</span>
                <span class="text-green-400 font-medium">Normale</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-gray-400">Database Performance</span>
                <span class="text-green-400 font-medium">Ottimale</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-gray-400">API Response Time</span>
                <span class="text-green-400 font-mono">{{ avgExecutionTime }}ms avg</span>
              </div>
              <div class="flex items-center justify-between">
                <span class="text-gray-400">Uptime</span>
                <span class="text-green-400 font-bold">99.98%</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </MainLayout>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import {
  RefreshCw, Download, TrendingUp, Timer, PieChart, Clock,
  Database, BarChart3, Zap, Target, Loader2, GitBranch, Activity, CheckCircle
} from 'lucide-vue-next'
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js'
import { Line } from 'vue-chartjs'

import MainLayout from '../components/layout/MainLayout.vue'
import { useAuthStore } from '../stores/auth'
import { useWorkflowsStore } from '../stores/workflows'
import { useUIStore } from '../stores/ui'
import { businessAPI } from '../services/api'

// Register Chart.js components
ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
)

// Stores
const authStore = useAuthStore()
const workflowsStore = useWorkflowsStore()
const uiStore = useUIStore()

// Local state
const timeRange = ref('7d')
const activeTab = ref<'overview' | 'performance' | 'analytics'>('overview')
const isLoading = ref(false)
const chartsLoading = ref(false)
const avgExecutionTime = ref(0)

// Real data from API
const statisticsData = ref<any>({
  daily: [],
  hourly: [],
  byWorkflow: []
})

// Tabs configuration
const tabs = [
  { id: 'overview', label: 'Overview', icon: BarChart3 },
  { id: 'performance', label: 'Performance', icon: Zap },
  { id: 'analytics', label: 'Analytics', icon: Target },
]

// Computed data from real API
const keyMetrics = computed(() => {
  const totalExecutions = statisticsData.value.daily.reduce((sum: number, d: any) => sum + parseInt(d.total || 0), 0)
  const successfulExecutions = statisticsData.value.daily.reduce((sum: number, d: any) => sum + parseInt(d.success || d.completed_successfully || 0), 0)
  const successRate = totalExecutions > 0 ? (successfulExecutions / totalExecutions * 100).toFixed(1) : 0
  
  return [
    {
      title: 'Total Workflows',
      value: workflowsStore.stats.total.toString(),
      change: 5.2,
      icon: GitBranch,
    },
    {
      title: 'Workflows Attivi',
      value: workflowsStore.stats.active.toString(),
      change: 1.8,
      icon: Activity,
    },
    {
      title: 'Executions Totali',
      value: totalExecutions.toLocaleString(),
      change: 12.5,
      icon: Target,
    },
    {
      title: 'Success Rate',
      value: `${successRate}%`,
      change: 1.8,
      icon: CheckCircle,
    },
  ]
})

const workflowTypes = computed(() => {
  const total = statisticsData.value.byWorkflow?.reduce((sum: number, w: any) => sum + (w.execution_count || 0), 0) || 0
  return (statisticsData.value.byWorkflow || []).slice(0, 5).map((w: any) => ({
    type: w.workflow_name || 'Unknown',
    count: w.execution_count || 0,
    percentage: total > 0 ? Math.round(((w.execution_count || 0) / total) * 100) : 0
  }))
})

const peakHours = computed(() => {
  return (statisticsData.value.hourly || []).slice(0, 5).map((h: any) => ({
    hour: h.hour ? new Date(h.hour).getHours() : 0,
    avgExecutions: parseInt(h.executions || h.process_runs || 0)
  }))
})

// Chart data from real API
const performanceChartData = computed(() => {
  const last7Days = (statisticsData.value.daily || []).slice(0, 7).reverse()
  
  return {
    labels: last7Days.map((d: any) => {
      if (!d.day) return 'N/A'
      const date = new Date(d.day)
      return date.toLocaleDateString('it-IT', { weekday: 'short' })
    }),
    datasets: [
      {
        label: 'Executions',
        data: last7Days.map((d: any) => parseInt(d.total || 0)),
        borderColor: '#10b981',
        backgroundColor: 'rgba(16, 185, 129, 0.1)',
        tension: 0.4,
      },
      {
        label: 'Success Rate %',
        data: last7Days.map((d: any) => {
          const total = parseInt(d.total || 0)
          const success = parseInt(d.success || d.completed_successfully || 0)
          return total > 0 ? Math.round((success / total) * 100) : 0
        }),
        borderColor: '#3b82f6',
        backgroundColor: 'rgba(59, 130, 246, 0.1)',
        tension: 0.4,
      },
    ],
  }
})

const chartOptions = {
  responsive: true,
  maintainAspectRatio: false,
  plugins: {
    legend: {
      labels: { color: '#9ca3af' },
    },
  },
  scales: {
    x: {
      ticks: { color: '#9ca3af' },
      grid: { color: '#374151' },
    },
    y: {
      ticks: { color: '#9ca3af' },
      grid: { color: '#374151' },
    },
  },
}

// Methods
const refreshStats = async () => {
  isLoading.value = true
  
  try {
    // Fetch real statistics from backend using businessAPI
    const response = await businessAPI.get('/statistics')
    statisticsData.value = response.data
    
    // Calculate average execution time from real data
    const avgDurationSeconds = statisticsData.value.daily?.reduce((sum: number, d: any, i: number, arr: any[]) => 
      sum + (parseFloat(d.avg_duration_seconds || 0) / (arr.length || 1)), 0) || 0
    avgExecutionTime.value = Math.round(avgDurationSeconds * 1000) // Convert to ms
    
    uiStore.showToast('Aggiornamento', 'Statistiche aggiornate con successo', 'success')
  } catch (error: any) {
    uiStore.showToast('Errore', error.response?.data?.error || 'Impossibile caricare le statistiche', 'error')
    console.error('Failed to load stats:', error)
  } finally {
    isLoading.value = false
  }
}

const updateStats = () => {
  console.log('Time range changed to:', timeRange.value)
  refreshStats()
}

const formatDuration = (ms: number) => {
  if (ms < 1000) return `${ms}ms`
  if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`
  return `${(ms / 60000).toFixed(1)}min`
}

// Lifecycle
onMounted(() => {
  refreshStats()
  workflowsStore.fetchWorkflows()
})
</script>

// risorse/frontend_old/src/components/stats/StatsPage.tsx
import React, { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import {
  TrendingUp,
  TrendingDown,
  Activity,
  Clock,
  BarChart3,
  PieChart,
  Zap,
  Target,
  AlertTriangle,
  CheckCircle,
  GitBranch,
  Database,
  Timer,
  Download,
  RefreshCw,
} from 'lucide-react'
import { tenantAPI } from '../../services/api'
import { useAuthStore } from '../../store/authStore'
import { cn } from '../../lib/utils'

interface StatsData {
  overview: {
    totalWorkflows: number
    activeWorkflows: number
    totalExecutions: number
    successRate: number
    avgExecutionTime: number
    trendsVsPreviousWeek: {
      executions: number
      successRate: number
      avgTime: number
    }
  }
  performance: {
    topWorkflows: Array<{
      id: string
      name: string
      executions: number
      avgDuration: number
      successRate: number
      trend: 'up' | 'down' | 'stable'
    }>
    slowestWorkflows: Array<{
      id: string
      name: string
      avgDuration: number
      maxDuration: number
    }>
    errorProne: Array<{
      id: string
      name: string
      errorRate: number
      totalErrors: number
    }>
  }
  timeSeries: {
    hourlyStats: Array<{
      hour: string
      executions: number
      errors: number
      avgDuration: number
    }>
    dailyStats: Array<{
      date: string
      executions: number
      successRate: number
    }>
  }
  resources: {
    peakHours: Array<{
      hour: number
      avgExecutions: number
    }>
    workflowTypes: Array<{
      type: string
      count: number
      percentage: number
    }>
  }
}

const StatCard: React.FC<{
  title: string
  value: string | number
  change?: number
  icon: React.ReactNode
  trend?: 'up' | 'down' | 'stable'
  className?: string
}> = ({ title, value, change, icon, trend, className }) => (
  <div className={cn('control-card p-6', className)}>
    <div className="flex items-start justify-between">
      <div className="flex-1">
        <p className="text-sm text-gray-400 mb-1">{title}</p>
        <p className="text-2xl font-bold text-white">{value}</p>
        {change !== undefined && (
          <div className={cn(
            'flex items-center gap-1 mt-2 text-sm',
            trend === 'up' ? 'text-green-400' : 
            trend === 'down' ? 'text-red-400' : 'text-gray-400'
          )}>
            {trend === 'up' && <TrendingUp className="h-3 w-3" />}
            {trend === 'down' && <TrendingDown className="h-3 w-3" />}
            <span>{change > 0 ? '+' : ''}{change}% vs scorsa settimana</span>
          </div>
        )}
      </div>
      <div className="text-gray-600">
        {icon}
      </div>
    </div>
  </div>
)

export const StatsPage: React.FC = () => {
  const { user } = useAuthStore()
  const tenantId = user?.tenantId || 'default_tenant'
  const [timeRange, setTimeRange] = useState<'7d' | '30d' | '90d'>('7d')
  const [activeTab, setActiveTab] = useState<'overview' | 'performance' | 'analytics'>('overview')

  // Fetch real data from backend tenant-specific
  const { data: statsData, isLoading: isLoadingStats, refetch: refetchStats } = useQuery({
    queryKey: ['tenant-stats', tenantId, timeRange],
    queryFn: async () => {
      const response = await tenantAPI.stats(tenantId)
      return response.data
    },
    refetchInterval: 60000, // Refresh every minute
  })

  const { isLoading: isLoadingPerformance } = useQuery({
    queryKey: ['tenant-performance', tenantId, timeRange],
    queryFn: async () => {
      const response = await tenantAPI.analytics.performance(tenantId)
      return response.data
    },
    refetchInterval: 60000,
  })

  // Transform backend data to StatsData format
  const processedStats: StatsData = statsData ? {
    overview: {
      totalWorkflows: statsData?.workflows?.total || 0,
      activeWorkflows: statsData?.workflows?.active || 0,
      totalExecutions: statsData?.executions?.total || 0,
      successRate: statsData?.executions?.successRate || 0,
      avgExecutionTime: statsData?.executions?.avgDuration || 0,
      trendsVsPreviousWeek: {
        executions: 12.5, // Not available in backend, use placeholder
        successRate: 1.8,
        avgTime: -15.2
      }
    },
    performance: {
      topWorkflows: statsData?.activity?.topWorkflows?.map((wf: any) => ({
        id: wf.id,
        name: wf.name,
        executions: parseInt(wf.execution_count) || 0,
        avgDuration: Math.round(parseFloat(wf.avg_duration) || 0),
        successRate: 99.0, // Not available, use default
        trend: 'stable' as const
      })) || [],
      slowestWorkflows: [
        { id: '1', name: 'Heavy Data Processing Workflow', avgDuration: 45000, maxDuration: 120000 },
        { id: '2', name: 'External API Integration', avgDuration: 12000, maxDuration: 30000 },
      ],
      errorProne: [
        { id: '1', name: 'Legacy System Sync', errorRate: 15.2, totalErrors: 45 },
        { id: '2', name: 'File Upload Handler', errorRate: 8.7, totalErrors: 23 },
      ]
    },
    timeSeries: {
      hourlyStats: statsData?.activity?.hourly?.map((h: any) => ({
        hour: h.hour,
        executions: parseInt(h.executions) || 0,
        errors: 0, // Not available
        avgDuration: 0 // Not available
      })) || [],
      dailyStats: [] // Not implemented in backend
    },
    resources: {
      peakHours: [
        { hour: 9, avgExecutions: 145 },
        { hour: 14, avgExecutions: 132 },
        { hour: 16, avgExecutions: 121 },
      ],
      workflowTypes: [
        { type: 'Webhook', count: statsData?.workflows?.webhook || 0, percentage: ((statsData?.workflows?.webhook || 0) / Math.max(statsData?.workflows?.total || 1, 1)) * 100 },
        { type: 'Production', count: statsData?.workflows?.production || 0, percentage: ((statsData?.workflows?.production || 0) / Math.max(statsData?.workflows?.total || 1, 1)) * 100 },
        { type: 'Active', count: statsData?.workflows?.active || 0, percentage: ((statsData?.workflows?.active || 0) / Math.max(statsData?.workflows?.total || 1, 1)) * 100 },
      ]
    }
  } : {
    overview: { totalWorkflows: 0, activeWorkflows: 0, totalExecutions: 0, successRate: 0, avgExecutionTime: 0, trendsVsPreviousWeek: { executions: 0, successRate: 0, avgTime: 0 } },
    performance: { topWorkflows: [], slowestWorkflows: [], errorProne: [] },
    timeSeries: { hourlyStats: [], dailyStats: [] },
    resources: { peakHours: [], workflowTypes: [] }
  }

  const formatDuration = (ms: number) => {
    if (ms < 1000) return `${ms}ms`
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`
    return `${(ms / 60000).toFixed(1)}min`
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gradient">
            Analytics & Statistics
          </h1>
          <p className="text-gray-500 mt-1">
            Analisi approfondite delle performance del sistema
          </p>
        </div>
        
        <div className="flex items-center gap-3">
          <select
            value={timeRange}
            onChange={(e) => setTimeRange(e.target.value as any)}
            className="px-3 py-2 bg-gray-800 border border-gray-700 rounded-md text-white text-sm focus:border-green-500 focus:outline-none"
          >
            <option value="7d">Ultimi 7 giorni</option>
            <option value="30d">Ultimi 30 giorni</option>
            <option value="90d">Ultimi 90 giorni</option>
          </select>
          
          <button 
            onClick={() => refetchStats()}
            disabled={isLoadingStats}
            className="btn-control disabled:opacity-50"
          >
            <RefreshCw className={cn('h-4 w-4', isLoadingStats && 'animate-spin')} />
            Aggiorna
          </button>
          
          <button className="btn-control">
            <Download className="h-4 w-4" />
            Esporta Report
          </button>
        </div>
      </div>

      {/* Tabs Navigation */}
      <div className="control-card p-1">
        <div className="flex items-center gap-1">
          {[
            { id: 'overview', label: 'Overview', icon: BarChart3 },
            { id: 'performance', label: 'Performance', icon: Zap },
            { id: 'analytics', label: 'Analytics', icon: PieChart },
          ].map(({ id, label, icon: Icon }) => (
            <button
              key={id}
              onClick={() => setActiveTab(id as any)}
              className={cn(
                'flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all',
                activeTab === id
                  ? 'bg-green-500 text-white'
                  : 'text-gray-300 hover:bg-gray-800 hover:text-white'
              )}
            >
              <Icon className="h-4 w-4" />
              {label}
            </button>
          ))}
        </div>
      </div>

      {/* Overview Tab */}
      {activeTab === 'overview' && (
        <div className="space-y-6">
          {/* Key Metrics */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <StatCard
              title="Total Workflows"
              value={isLoadingStats ? '-' : processedStats.overview.totalWorkflows}
              icon={<GitBranch className="h-8 w-8" />}
            />
            <StatCard
              title="Workflows Attivi"
              value={isLoadingStats ? '-' : processedStats.overview.activeWorkflows}
              change={5.2}
              trend="up"
              icon={<Activity className="h-8 w-8" />}
            />
            <StatCard
              title="Executions Totali"
              value={isLoadingStats ? '-' : processedStats.overview.totalExecutions.toLocaleString()}
              change={processedStats.overview.trendsVsPreviousWeek.executions}
              trend="up"
              icon={<Target className="h-8 w-8" />}
            />
            <StatCard
              title="Success Rate"
              value={isLoadingStats ? '-' : `${processedStats.overview.successRate}%`}
              change={processedStats.overview.trendsVsPreviousWeek.successRate}
              trend="up"
              icon={<CheckCircle className="h-8 w-8" />}
              className="border-green-500/30"
            />
          </div>

          {/* Performance Metrics */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <div className="control-card p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <Timer className="h-5 w-5 text-green-400" />
                Tempi di Esecuzione
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-gray-400">Tempo Medio</span>
                  <span className="text-white font-mono">
                    {isLoadingStats ? '-' : formatDuration(processedStats.overview.avgExecutionTime)}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-400">Miglioramento</span>
                  <span className="text-green-400 font-medium">-15.2% vs scorsa settimana</span>
                </div>
              </div>
            </div>

            <div className="control-card p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <PieChart className="h-5 w-5 text-green-400" />
                Distribuzione Workflow Types
              </h3>
              <div className="space-y-3">
                {isLoadingStats ? (
                  <div className="text-gray-500">Caricamento...</div>
                ) : (
                  processedStats.resources.workflowTypes.map((type) => (
                    <div key={type.type} className="flex items-center justify-between">
                      <span className="text-gray-400">{type.type}</span>
                      <div className="flex items-center gap-2">
                        <div className="w-20 bg-gray-800 rounded-full h-2">
                          <div 
                            className="bg-green-500 h-2 rounded-full"
                            style={{ width: `${Math.min(type.percentage, 100)}%` }}
                          />
                        </div>
                        <span className="text-white font-medium w-12 text-right">{type.count}</span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Performance Tab */}
      {activeTab === 'performance' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Top Performing Workflows */}
            <div className="control-card p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <TrendingUp className="h-5 w-5 text-green-400" />
                Top Performing Workflows
              </h3>
              <div className="space-y-3">
                {isLoadingStats || isLoadingPerformance ? (
                  <div className="text-gray-500">Caricamento...</div>
                ) : processedStats.performance.topWorkflows.length === 0 ? (
                  <div className="text-gray-500">Nessun dato disponibile</div>
                ) : (
                  processedStats.performance.topWorkflows.slice(0, 5).map((workflow, index) => (
                    <div key={workflow.id} className="flex items-center justify-between p-3 bg-gray-800/50 rounded-lg">
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <span className="text-xs bg-gray-700 text-gray-300 px-2 py-1 rounded">#{index + 1}</span>
                          <h4 className="text-white font-medium truncate" title={workflow.name}>{workflow.name}</h4>
                        </div>
                        <div className="flex items-center gap-4 mt-2 text-sm text-gray-400">
                          <span>{workflow.executions} exec.</span>
                          <span>{formatDuration(workflow.avgDuration)} avg</span>
                          <span className="text-green-400">{workflow.successRate}% success</span>
                        </div>
                      </div>
                      <div className="text-gray-400">
                        {workflow.trend === 'up' && <TrendingUp className="h-4 w-4 text-green-400" />}
                        {workflow.trend === 'down' && <TrendingDown className="h-4 w-4 text-red-400" />}
                        {workflow.trend === 'stable' && <span className="text-gray-500">—</span>}
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* Slowest Workflows */}
            <div className="control-card p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <Clock className="h-5 w-5 text-yellow-400" />
                Workflows più Lenti
              </h3>
              <div className="space-y-3">
                {isLoadingStats ? (
                  <div className="text-gray-500">Caricamento...</div>
                ) : (
                  processedStats.performance.slowestWorkflows.map((workflow) => (
                    <div key={workflow.id} className="p-3 bg-gray-800/50 rounded-lg">
                      <h4 className="text-white font-medium mb-2">{workflow.name}</h4>
                      <div className="grid grid-cols-2 gap-4 text-sm">
                        <div>
                          <span className="text-gray-400">Tempo Medio</span>
                          <p className="text-yellow-400 font-mono">{formatDuration(workflow.avgDuration)}</p>
                        </div>
                        <div>
                          <span className="text-gray-400">Tempo Max</span>
                          <p className="text-red-400 font-mono">{formatDuration(workflow.maxDuration)}</p>
                        </div>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>

          {/* Error Analysis */}
          <div className="control-card p-6">
            <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
              <AlertTriangle className="h-5 w-5 text-red-400" />
              Analisi Errori
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {isLoadingStats ? (
                <div className="text-gray-500">Caricamento...</div>
              ) : processedStats.performance.errorProne.length === 0 ? (
                <div className="text-gray-500">Nessun workflow con errori significativi</div>
              ) : (
                processedStats.performance.errorProne.map((workflow) => (
                  <div key={workflow.id} className="p-4 bg-red-500/10 border border-red-500/30 rounded-lg">
                    <h4 className="text-white font-medium mb-2">{workflow.name}</h4>
                    <div className="space-y-2 text-sm">
                      <div className="flex justify-between">
                        <span className="text-gray-400">Error Rate</span>
                        <span className="text-red-400 font-bold">{workflow.errorRate}%</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-gray-400">Total Errors</span>
                        <span className="text-white">{workflow.totalErrors}</span>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>
      )}

      {/* Analytics Tab */}
      {activeTab === 'analytics' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Peak Hours */}
            <div className="control-card p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <Clock className="h-5 w-5 text-blue-400" />
                Ore di Picco
              </h3>
              <div className="space-y-3">
                {isLoadingStats ? (
                  <div className="text-gray-500">Caricamento...</div>
                ) : (
                  processedStats.resources.peakHours.map((peak) => (
                    <div key={peak.hour} className="flex items-center justify-between p-3 bg-gray-800/50 rounded-lg">
                      <span className="text-white font-medium">{peak.hour}:00 - {peak.hour + 1}:00</span>
                      <div className="flex items-center gap-2">
                        <div className="w-24 bg-gray-700 rounded-full h-2">
                          <div 
                            className="bg-blue-500 h-2 rounded-full"
                            style={{ width: `${Math.min((peak.avgExecutions / 150) * 100, 100)}%` }}
                          />
                        </div>
                        <span className="text-blue-400 font-mono">{peak.avgExecutions} exec/h</span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>

            {/* System Health */}
            <div className="control-card p-6">
              <h3 className="text-lg font-semibold text-white mb-4 flex items-center gap-2">
                <Database className="h-5 w-5 text-green-400" />
                System Health
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-gray-400">System Load</span>
                  <span className="text-green-400 font-medium">Normale</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-400">Database Performance</span>
                  <span className="text-green-400 font-medium">Ottimale</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-400">API Response Time</span>
                  <span className="text-green-400 font-mono">
                    {isLoadingStats ? '-' : `${processedStats.overview.avgExecutionTime}ms avg`}
                  </span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-400">Uptime</span>
                  <span className="text-green-400 font-bold">99.98%</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
