// frontend/src/components/executions/ExecutionsPage.tsx
import React, { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { 
  Activity, 
  Play, 
  CheckCircle, 
  XCircle, 
  Clock, 
  Search, 
  RefreshCw,
  Filter,
  Eye,
  RotateCcw
} from 'lucide-react'
import { executionsAPI } from '../../services/api'
import { cn } from '../../lib/utils'

export const ExecutionsPage: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('')
  const [statusFilter, setStatusFilter] = useState<'all' | 'success' | 'error' | 'running'>('all')
  
  // Carica le esecuzioni in modo sicuro
  const { data: executions, isLoading, error, refetch } = useQuery({
    queryKey: ['executions-list'],
    queryFn: async () => {
      try {
        // Fix: usa endpoint tenant per dati reali
        const response = await fetch('/api/tenant/client_simulation_a/executions', {
          headers: {
            'Authorization': `Bearer ${localStorage.getItem('token')}`,
            'Content-Type': 'application/json'
          }
        })
        const data = await response.json()
        return data.executions || []
      } catch (err) {
        console.error('Error loading executions:', err)
        return []
      }
    },
    refetchInterval: 30000,
    retry: 1,
    retryOnMount: false
  })

  const filteredExecutions = (executions || []).filter((execution: any) => {
    const matchesSearch = execution.workflowName?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         execution.id?.toLowerCase().includes(searchTerm.toLowerCase())
    const matchesStatus = statusFilter === 'all' || execution.status === statusFilter
    return matchesSearch && matchesStatus
  })

  const getStatusInfo = (status: string) => {
    switch (status) {
      case 'success':
        return { icon: CheckCircle, color: 'text-green-400', bgColor: 'bg-green-500/10', label: 'Success' }
      case 'error':
        return { icon: XCircle, color: 'text-red-400', bgColor: 'bg-red-500/10', label: 'Error' }
      case 'running':
        return { icon: Play, color: 'text-blue-400', bgColor: 'bg-blue-500/10', label: 'Running' }
      default:
        return { icon: Clock, color: 'text-gray-400', bgColor: 'bg-gray-500/10', label: 'Unknown' }
    }
  }

  const formatDuration = (ms: number) => {
    if (ms < 1000) return `${ms}ms`
    if (ms < 60000) return `${(ms / 1000).toFixed(1)}s`
    return `${(ms / 60000).toFixed(1)}m`
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gradient">
            ⚡ Workflow Executions
          </h1>
          <p className="text-gray-500 mt-1">
            Monitora l'esecuzione dei tuoi workflow in tempo reale
          </p>
        </div>
        
        <div className="flex items-center gap-3">
          <button 
            onClick={() => refetch()}
            disabled={isLoading}
            className="btn-control disabled:opacity-50"
          >
            <RefreshCw className={cn('h-4 w-4', isLoading && 'animate-spin')} />
            Aggiorna
          </button>
        </div>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
        <div className="control-card p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-400">Total Executions</p>
              <p className="text-2xl font-bold text-blue-400">
                {isLoading ? '-' : (executions?.length || 0)}
              </p>
            </div>
            <Activity className="h-8 w-8 text-blue-500" />
          </div>
        </div>

        <div className="control-card p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-400">Successful</p>
              <p className="text-2xl font-bold text-green-400">
                {isLoading ? '-' : (executions?.filter((e: any) => e.status === 'success').length || 0)}
              </p>
            </div>
            <CheckCircle className="h-8 w-8 text-green-500" />
          </div>
        </div>

        <div className="control-card p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-400">Failed</p>
              <p className="text-2xl font-bold text-red-400">
                {isLoading ? '-' : (executions?.filter((e: any) => e.status === 'error').length || 0)}
              </p>
            </div>
            <XCircle className="h-8 w-8 text-red-500" />
          </div>
        </div>

        <div className="control-card p-6">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm text-gray-400">Running</p>
              <p className="text-2xl font-bold text-yellow-400">
                {isLoading ? '-' : (executions?.filter((e: any) => e.status === 'running').length || 0)}
              </p>
            </div>
            <Play className="h-8 w-8 text-yellow-500" />
          </div>
        </div>
      </div>

      {/* Filters */}
      <div className="control-card p-4">
        <div className="flex flex-col lg:flex-row gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500" />
            <input
              type="text"
              placeholder="Cerca per workflow o ID esecuzione..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full pl-10 pr-4 py-2 bg-gray-800 border border-gray-700 rounded-md text-white text-sm focus:border-green-500 focus:outline-none"
            />
          </div>

          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value as any)}
            className="px-4 py-2 bg-gray-800 border border-gray-700 rounded-md text-white text-sm focus:border-green-500 focus:outline-none"
          >
            <option value="all">Tutti gli stati</option>
            <option value="success">Solo Successi</option>
            <option value="error">Solo Errori</option>
            <option value="running">Solo In Esecuzione</option>
          </select>
        </div>
      </div>

      {/* Content */}
      {error ? (
        <div className="control-card p-6">
          <div className="text-center text-red-400">
            ⚠️ Errore nel caricamento delle esecuzioni. Controlla la connessione al backend.
          </div>
        </div>
      ) : isLoading ? (
        <div className="control-card p-6">
          <div className="text-center text-gray-500">
            <RefreshCw className="h-6 w-6 animate-spin mx-auto mb-2" />
            Caricamento esecuzioni...
          </div>
        </div>
      ) : filteredExecutions.length === 0 ? (
        <div className="control-card p-6">
          <div className="text-center text-gray-500">
            {executions?.length === 0 ? 
              '📊 Nessuna esecuzione presente. I workflow verranno visualizzati qui una volta eseguiti.' :
              '🔍 Nessuna esecuzione corrisponde ai filtri selezionati.'
            }
          </div>
        </div>
      ) : (
        <div className="control-card overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead>
                <tr className="border-b border-gray-800">
                  <th className="text-left p-4 text-sm font-medium text-gray-400">Workflow</th>
                  <th className="text-left p-4 text-sm font-medium text-gray-400">Status</th>
                  <th className="text-left p-4 text-sm font-medium text-gray-400">Durata</th>
                  <th className="text-left p-4 text-sm font-medium text-gray-400">Avviato</th>
                  <th className="text-left p-4 text-sm font-medium text-gray-400">Azioni</th>
                </tr>
              </thead>
              <tbody>
                {filteredExecutions.map((execution: any) => {
                  const statusInfo = getStatusInfo(execution.status)
                  const StatusIcon = statusInfo.icon
                  
                  return (
                    <tr 
                      key={execution.id} 
                      className="border-b border-gray-800/50 hover:bg-gray-900/30 transition-colors"
                    >
                      <td className="p-4">
                        <div>
                          <div className="text-white font-medium">{execution.workflowName || 'Unknown Workflow'}</div>
                          <div className="text-xs text-gray-400">ID: {execution.id}</div>
                        </div>
                      </td>
                      
                      <td className="p-4">
                        <span className={cn(
                          'inline-flex items-center gap-1 px-2 py-1 rounded-md text-xs font-medium',
                          statusInfo.bgColor,
                          statusInfo.color
                        )}>
                          <StatusIcon className="h-3 w-3" />
                          {statusInfo.label}
                        </span>
                      </td>
                      
                      <td className="p-4">
                        <div className="text-white text-sm">
                          {execution.duration ? formatDuration(execution.duration) : '-'}
                        </div>
                      </td>
                      
                      <td className="p-4">
                        <div className="flex items-center gap-1 text-gray-400 text-sm">
                          <Clock className="h-3 w-3" />
                          {execution.startedAt ? 
                            new Date(execution.startedAt).toLocaleString('it-IT') : 
                            'N/A'
                          }
                        </div>
                      </td>
                      
                      <td className="p-4">
                        <div className="flex items-center gap-1">
                          <button className="p-1 text-gray-400 hover:text-blue-400 transition-colors">
                            <Eye className="h-4 w-4" />
                          </button>
                          <button className="p-1 text-gray-400 hover:text-green-400 transition-colors">
                            <RotateCcw className="h-4 w-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  )
                })}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/pages/ExecutionsPage.vue
<template>
  <MainLayout>
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold text-gradient">
            Executions - {{ authStore.tenantId }}
          </h1>
          <p class="text-gray-400 mt-1">
            Monitora le esecuzioni dei tuoi workflow
          </p>
        </div>
        
        <div class="flex items-center gap-3">
          <!-- Auto Refresh Toggle -->
          <div class="flex items-center gap-2">
            <input
              v-model="autoRefresh"
              type="checkbox"
              id="auto-refresh"
              class="w-4 h-4 text-green-500 bg-gray-900 border-gray-600 rounded focus:ring-green-500"
            />
            <label for="auto-refresh" class="text-sm text-white">
              Auto refresh
            </label>
          </div>
          
          <button 
            @click="refreshExecutions"
            :disabled="isLoading"
            class="btn-control"
          >
            <RefreshCw :class="{ 'animate-spin': isLoading }" class="h-4 w-4" />
            Refresh
          </button>
          
          <button class="btn-control">
            <Download class="h-4 w-4" />
            Esporta
          </button>
        </div>
      </div>

      <!-- Stats Cards -->
      <div class="grid grid-cols-2 md:grid-cols-5 gap-4">
        <div class="control-card p-4">
          <div class="text-center">
            <p class="text-2xl font-bold text-white">{{ executionStats.total }}</p>
            <p class="text-xs text-gray-400">Totali</p>
          </div>
        </div>
        
        <div class="control-card p-4">
          <div class="text-center">
            <p class="text-2xl font-bold text-green-400">{{ executionStats.success }}</p>
            <p class="text-xs text-gray-400">Success</p>
          </div>
        </div>
        
        <div class="control-card p-4">
          <div class="text-center">
            <p class="text-2xl font-bold text-red-400">{{ executionStats.error }}</p>
            <p class="text-xs text-gray-400">Error</p>
          </div>
        </div>
        
        <div class="control-card p-4">
          <div class="text-center">
            <p class="text-2xl font-bold text-blue-400">{{ executionStats.running }}</p>
            <p class="text-xs text-gray-400">Running</p>
          </div>
        </div>
        
        <div class="control-card p-4">
          <div class="text-center">
            <p class="text-2xl font-bold text-yellow-400">{{ executionStats.waiting }}</p>
            <p class="text-xs text-gray-400">Waiting</p>
          </div>
        </div>
      </div>

      <!-- Filters -->
      <div class="control-card p-4">
        <div class="grid grid-cols-1 lg:grid-cols-3 gap-4">
          <div class="relative">
            <Search class="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500" />
            <input
              v-model="searchTerm"
              type="text"
              placeholder="Cerca executions..."
              class="w-full pl-10 pr-4 py-2 bg-gray-800 border border-gray-700 rounded-md text-white text-sm focus:border-green-500 focus:outline-none"
            />
          </div>

          <select
            v-model="statusFilter"
            class="px-3 py-2 bg-gray-800 border border-gray-700 rounded-md text-white text-sm focus:border-green-500 focus:outline-none"
          >
            <option value="all">Any Status ({{ executionStats.total }})</option>
            <option value="success">Success ({{ executionStats.success }})</option>
            <option value="error">Error ({{ executionStats.error }})</option>
            <option value="running">Running ({{ executionStats.running }})</option>
            <option value="waiting">Waiting ({{ executionStats.waiting }})</option>
          </select>

          <select
            v-model="workflowFilter"
            class="px-3 py-2 bg-gray-800 border border-gray-700 rounded-md text-white text-sm focus:border-green-500 focus:outline-none"
          >
            <option value="all">All Workflows</option>
            <option
              v-for="workflow in workflowsStore.workflows"
              :key="workflow.id"
              :value="workflow.id"
            >
              {{ workflow.name }}
            </option>
          </select>
        </div>
      </div>

      <!-- Executions Table -->
      <div class="control-card overflow-hidden">
        <div class="overflow-x-auto">
          <table class="w-full">
            <thead>
              <tr class="border-b border-gray-800">
                <th class="text-left p-4 text-sm font-medium text-gray-400">
                  <input type="checkbox" class="w-4 h-4 bg-gray-900 border-gray-600 rounded" />
                </th>
                <th class="text-left p-4 text-sm font-medium text-gray-400">Workflow</th>
                <th class="text-left p-4 text-sm font-medium text-gray-400">Status</th>
                <th class="text-left p-4 text-sm font-medium text-gray-400">Started</th>
                <th class="text-left p-4 text-sm font-medium text-gray-400">Run Time</th>
                <th class="text-left p-4 text-sm font-medium text-gray-400">Exec. ID</th>
                <th class="text-left p-4 text-sm font-medium text-gray-400"></th>
              </tr>
            </thead>
            <tbody>
              <tr v-if="filteredExecutions.length === 0">
                <td colspan="7" class="p-8 text-center text-gray-500">
                  <Play class="h-8 w-8 mx-auto mb-2 text-gray-600" />
                  Nessuna execution trovata
                </td>
              </tr>
              
              <tr
                v-for="execution in filteredExecutions"
                :key="execution.id"
                class="border-b border-gray-800/50 hover:bg-gray-900/30 transition-colors"
              >
                <td class="p-4">
                  <input type="checkbox" class="w-4 h-4 bg-gray-900 border-gray-600 rounded" />
                </td>
                
                <td class="p-4">
                  <div class="font-medium text-white max-w-xs">
                    <span class="truncate block" :title="execution.workflow_name">
                      {{ execution.workflow_name }}
                    </span>
                  </div>
                </td>
                
                <td class="p-4">
                  <span 
                    class="inline-flex items-center gap-1.5 px-2 py-1 rounded-md text-xs font-medium border"
                    :class="getStatusClass(execution.status)"
                  >
                    <div class="w-1.5 h-1.5 rounded-full" :class="getStatusDot(execution.status)" />
                    {{ getStatusLabel(execution.status) }}
                  </span>
                </td>
                
                <td class="p-4 text-sm text-gray-300">
                  {{ formatTime(execution.started_at) }}
                </td>
                
                <td class="p-4 text-sm text-gray-300 font-mono">
                  {{ formatDuration(execution.duration_ms) }}
                </td>
                
                <td class="p-4 text-sm text-gray-300 font-mono">
                  {{ execution.id }}
                </td>
                
                <td class="p-4">
                  <button class="p-1 text-gray-400 hover:text-white transition-colors">
                    <MoreHorizontal class="h-4 w-4" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Pagination -->
      <div v-if="filteredExecutions.length > 0" class="flex items-center justify-between">
        <p class="text-sm text-gray-400">
          Visualizzando {{ filteredExecutions.length }} di {{ executions.length }} executions
        </p>
        <div class="flex items-center gap-2">
          <button class="btn-control text-xs px-3 py-1" disabled>
            Precedente
          </button>
          <button class="btn-control text-xs px-3 py-1" disabled>
            Successiva
          </button>
        </div>
      </div>
    </div>
  </MainLayout>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import {
  RefreshCw, Download, Search, Play, CheckCircle, XCircle,
  Clock, Pause, MoreHorizontal
} from 'lucide-vue-next'
import MainLayout from '../components/layout/MainLayout.vue'
import { useAuthStore } from '../stores/auth'
import { useWorkflowsStore } from '../stores/workflows'
import { useUIStore } from '../stores/ui'
import { businessAPI } from '../services/api'
import webSocketService from '../services/websocket'
import type { Execution } from '../types'

// Stores
const authStore = useAuthStore()
const workflowsStore = useWorkflowsStore()
const uiStore = useUIStore()

// Local state
const isLoading = ref(false)
const autoRefresh = ref(true)
const searchTerm = ref('')
const statusFilter = ref<'all' | 'success' | 'error' | 'running' | 'waiting'>('all')
const workflowFilter = ref('all')
const executions = ref<Execution[]>([])

// Auto-refresh interval
let refreshInterval: NodeJS.Timeout

// Computed
const executionStats = computed(() => ({
  total: executions.value.length,
  success: executions.value.filter(e => e.status === 'success').length,
  error: executions.value.filter(e => e.status === 'error').length,
  running: executions.value.filter(e => e.status === 'running').length,
  waiting: executions.value.filter(e => e.status === 'waiting').length,
}))

const filteredExecutions = computed(() => {
  return executions.value.filter((execution) => {
    // Search filter
    const matchesSearch = execution.workflow_name.toLowerCase().includes(searchTerm.value.toLowerCase()) ||
                         execution.id.toLowerCase().includes(searchTerm.value.toLowerCase())
    
    // Status filter
    const matchesStatus = statusFilter.value === 'all' || execution.status === statusFilter.value
    
    // Workflow filter
    const matchesWorkflow = workflowFilter.value === 'all' || execution.workflow_id === workflowFilter.value
    
    return matchesSearch && matchesStatus && matchesWorkflow
  })
})

// Methods
const refreshExecutions = async () => {
  isLoading.value = true
  
  try {
    // Fetch real executions from backend API using businessAPI
    const response = await businessAPI.get('/process-runs')
    const data = response.data
    
    // Map backend data to our frontend format
    executions.value = (data.data || []).map((run: any) => ({
      id: run.run_id,
      workflow_id: run.process_id,
      workflow_name: run.process_name,
      status: mapBackendStatus(run.business_status),
      mode: run.is_completed ? 'webhook' : 'manual',
      started_at: run.start_time,
      stopped_at: run.end_time,
      duration_ms: run.duration_ms,
      business_status: run.business_status,
      issue_description: run.issue_description
    }))
    
    if (executions.value.length > 0) {
      uiStore.showToast('Aggiornamento', `${executions.value.length} executions caricate`, 'success')
    }
    
  } catch (error: any) {
    uiStore.showToast('Errore', error.response?.data?.error || 'Impossibile caricare le executions', 'error')
    console.error('Failed to load executions:', error)
    
    // Fallback to empty array on error
    executions.value = []
  } finally {
    isLoading.value = false
  }
}

// Helper to map backend status to frontend status
const mapBackendStatus = (businessStatus: string): string => {
  switch (businessStatus) {
    case 'Completed Successfully':
      return 'success'
    case 'Requires Attention':
      return 'error'
    case 'In Progress':
      return 'running'
    default:
      return 'waiting'
  }
}

// Status helpers - same pattern as n8n
const getStatusClass = (status: string | null) => {
  switch (status) {
    case 'success':
      return 'text-green-400 bg-green-500/10 border-green-500/30'
    case 'error':
      return 'text-red-400 bg-red-500/10 border-red-500/30'
    case 'running':
      return 'text-blue-400 bg-blue-500/10 border-blue-500/30'
    case 'waiting':
      return 'text-yellow-400 bg-yellow-500/10 border-yellow-500/30'
    default:
      return 'text-gray-400 bg-gray-500/10 border-gray-500/30'
  }
}

const getStatusDot = (status: string | null) => {
  switch (status) {
    case 'success': return 'bg-green-500'
    case 'error': return 'bg-red-500'
    case 'running': return 'bg-blue-500'
    case 'waiting': return 'bg-yellow-500'
    default: return 'bg-gray-500'
  }
}

const getStatusLabel = (status: string | null) => {
  switch (status) {
    case 'success': return 'Success'
    case 'error': return 'Error'
    case 'running': return 'Running'
    case 'waiting': return 'Waiting'
    default: return 'Unknown'
  }
}

const formatTime = (dateString: string) => {
  const date = new Date(dateString)
  const now = new Date()
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
  const executionDate = new Date(date.getFullYear(), date.getMonth(), date.getDate())
  
  const timeStr = date.toLocaleTimeString('it-IT', { 
    hour: '2-digit', 
    minute: '2-digit',
    second: '2-digit'
  })
  
  if (executionDate.getTime() === today.getTime()) {
    return timeStr
  }
  
  return `${date.toLocaleDateString('it-IT', { 
    month: 'short', 
    day: '2-digit' 
  })}, ${timeStr}`
}

const formatDuration = (ms?: number) => {
  if (!ms) return '-'
  if (ms < 1000) return `${ms}ms`
  if (ms < 60000) return `${Math.round(ms / 1000 * 10) / 10}s`
  return `${Math.round(ms / 60000 * 10) / 10}min`
}

// Auto-refresh setup
watch(autoRefresh, (enabled) => {
  if (enabled) {
    webSocketService.startAutoRefresh('executions', refreshExecutions, 5000)
  } else {
    webSocketService.stopAutoRefresh('executions')
  }
})

// Lifecycle
onMounted(() => {
  refreshExecutions()
  workflowsStore.fetchWorkflows() // For workflow filter
  
  if (autoRefresh.value) {
    webSocketService.startAutoRefresh('executions', refreshExecutions, 5000)
  }
  
  // Listen for real-time execution events
  window.addEventListener('execution:started', refreshExecutions)
  window.addEventListener('execution:completed', refreshExecutions)
})

onUnmounted(() => {
  // Stop auto-refresh
  webSocketService.stopAutoRefresh('executions')
  
  // Clean up event listeners
  window.removeEventListener('execution:started', refreshExecutions)
  window.removeEventListener('execution:completed', refreshExecutions)
})
</script>
