// frontend/src/components/auth/LoginPage.tsx
import React, { useState } from 'react'
import { Navigate } from 'react-router-dom'
import { Button } from '../ui/button'
import { Input } from '../ui/input'
import { Label } from '../ui/label'
import { Card } from '../ui/card'
import { useToast } from '../../hooks/use-toast'
import { Eye, EyeOff, Loader2 } from 'lucide-react'
import BackToTopButton from './BackToTopButton'
import { useAuthStore } from '../../store/authStore'

// Costanti di testo
const LOGIN_TITLE = "Bentornato"
const LOGIN_DESCRIPTION = "Accedi per gestire i tuoi Ai Agent."
const BRAND_TITLE = "I primi Ai business Agent in Italia"
const BRAND_DESCRIPTION = "Trasformiamo il modo di lavorare delle aziende attraverso l'intelligenza artificiale. Benvenuto!"

export const LoginPage: React.FC = () => {
  const [isLoading, setIsLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)
  const [formData, setFormData] = useState({
    email: 'admin@pilotpro.local',
    password: 'admin123',
  })
  const { toast } = useToast()
  const { login, isAuthenticated } = useAuthStore()

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsLoading(true)

    setTimeout(async () => {
      setIsLoading(false)
      try {
        await login(formData.email, formData.password)
        toast({
          title: "Login effettuato con successo!",
          description: "Benvenuto in PilotPro Control Center",
        })
      } catch (error: any) {
        toast({
          title: "Errore di login",
          description: error.message || "Credenziali non valide",
          variant: "destructive",
        })
      }
    }, 1000)
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { name, value } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: value
    }))
  }

  if (isAuthenticated) {
    return <Navigate to="/" replace />
  }

  return (
    <div className="min-h-screen">
      <div className="flex min-h-screen">
        {/* Left Side - Integrations Gradient with Brand Texts */}
        <div className="hidden lg:flex lg:w-1/2 relative bg-black overflow-hidden">
          {/* Same gradient as integrations section */}
          <div className="absolute inset-0 bg-gradient-to-br from-yellow-400/30 via-lime-400/25 to-green-400/30"></div>
          <div className="absolute inset-0 bg-gradient-to-tr from-green-400/20 via-transparent to-yellow-400/20"></div>
          
          <div className="relative z-10 flex flex-col justify-center items-center text-center px-12 w-full">
            <div className="max-w-2xl">
              {/* Logo PilotPro Testuale */}
              <div className="mb-8">
                <h2 className="text-3xl sm:text-4xl md:text-5xl font-light tracking-tight">
                  <span className="text-white">Pilot</span>
                  <span className="text-green-400">Pro</span>
                </h2>
              </div>
              
              <h1 className="text-4xl sm:text-5xl md:text-6xl text-white mb-6 tracking-tight leading-tight" style={{ fontWeight: '300' }}>
                {BRAND_TITLE}
              </h1>
              <p className="text-lg md:text-xl text-gray-300 leading-relaxed" style={{ fontWeight: '200' }}>
                {BRAND_DESCRIPTION}
              </p>
            </div>
          </div>
        </div>

        {/* Right Side - Black Background with Auth Form */}
        <div className="w-full lg:w-1/2 bg-black flex flex-col">
          <div className="flex-1 flex items-center justify-center px-8 py-12">
            <div className="w-full max-w-md">
              <Card className="bg-gray-900 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-700 p-6 text-left relative">
                <div>
                  <h3 className="text-lg md:text-xl text-white mb-4" style={{ fontWeight: '300' }}>
                    {LOGIN_TITLE}
                  </h3>
                  <p className="text-base text-gray-300 leading-relaxed mb-6" style={{ fontWeight: '200' }}>
                    {LOGIN_DESCRIPTION}
                  </p>
                  <form onSubmit={handleSubmit} className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="email" className="text-sm text-gray-300" style={{ fontWeight: '300' }}>
                        Email
                      </Label>
                      <Input
                        id="email"
                        name="email"
                        type="email"
                        placeholder="inserisci la tua email"
                        value={formData.email}
                        onChange={handleInputChange}
                        required
                        className="bg-gray-800 border-gray-700 text-white placeholder-gray-500 focus:border-green-400 focus:ring-green-400"
                      />
                    </div>
                    
                    <div className="space-y-2">
                      <Label htmlFor="password" className="text-sm text-gray-300" style={{ fontWeight: '300' }}>
                        Password
                      </Label>
                      <div className="relative">
                        <Input
                          id="password"
                          name="password"
                          type={showPassword ? "text" : "password"}
                          placeholder="inserisci la tua password"
                          value={formData.password}
                          onChange={handleInputChange}
                          required
                          className="bg-gray-800 border-gray-700 text-white placeholder-gray-500 focus:border-green-400 focus:ring-green-400 pr-10"
                        />
                        <Button
                          type="button"
                          variant="ghost"
                          size="sm"
                          className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-gray-700"
                          onClick={() => setShowPassword(!showPassword)}
                        >
                          {showPassword ? (
                            <EyeOff className="h-4 w-4 text-gray-400" />
                          ) : (
                            <Eye className="h-4 w-4 text-gray-400" />
                          )}
                        </Button>
                      </div>
                    </div>
                    
                    <Button 
                      type="submit" 
                      className="w-full bg-green-600 hover:bg-green-700 text-white rounded-lg shadow-lg"
                      disabled={isLoading}
                    >
                      {isLoading ? (
                        <>
                          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                          Accesso in corso...
                        </>
                      ) : (
                        "Accedi"
                      )}
                    </Button>
                  </form>
                  
                </div>
              </Card>
            </div>
          </div>
        </div>
      </div>
      <BackToTopButton />
    </div>
  )
}

// frontend/src/pages/LoginPage.vue
<template>
  <div class="min-h-screen">
    <!-- Header -->
    <div class="relative z-50">
      <header class="bg-black/90 backdrop-blur-lg border-b border-gray-800/50">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div class="flex justify-between items-center py-4">
            <div class="flex items-center">
              <span class="text-xl font-bold text-white">PilotPro</span>
            </div>
            <nav class="hidden md:flex space-x-8">
              <a href="#" class="text-gray-300 hover:text-white transition-colors">Prodotti AI</a>
              <a href="#" class="text-gray-300 hover:text-white transition-colors">Azienda</a>
              <a href="#" class="text-gray-300 hover:text-white transition-colors">Risorse</a>
              <a href="#" class="text-green-400 hover:text-green-300 transition-colors">Accedi</a>
            </nav>
          </div>
        </div>
      </header>
    </div>

    <div class="flex min-h-screen pt-16">
      <!-- Left Side - Integrations Gradient with Brand Texts -->
      <div class="hidden lg:flex lg:w-1/2 relative bg-black overflow-hidden">
        <!-- Same gradient as integrations section -->
        <div class="absolute inset-0 bg-gradient-to-br from-yellow-400/30 via-lime-400/25 to-green-400/30"></div>
        <div class="absolute inset-0 bg-gradient-to-tr from-green-400/20 via-transparent to-yellow-400/20"></div>
        
        <div class="relative z-10 flex flex-col justify-center items-center text-center px-12 w-full">
          <div class="max-w-2xl">
            <h1 class="text-4xl sm:text-5xl md:text-6xl text-white mb-6 tracking-tight leading-tight" style="font-weight: 300;">
              {{ BRAND_TITLE }}
            </h1>
            <p class="text-lg md:text-xl text-gray-300 leading-relaxed" style="font-weight: 200;">
              {{ BRAND_DESCRIPTION }}
            </p>
          </div>
        </div>
      </div>

      <!-- Right Side - Black Background with Auth Form -->
      <div class="w-full lg:w-1/2 bg-black flex flex-col">
        <div class="flex-1 flex items-center justify-center px-8 py-12">
          <div class="w-full max-w-md">
            <div class="bg-gray-900 rounded-2xl shadow-lg hover:shadow-xl transition-all duration-300 transform hover:-translate-y-1 border border-gray-700 p-6 text-left relative">
              <div>
                <h3 class="text-lg md:text-xl text-white mb-4" style="font-weight: 300;">
                  {{ isSignUp ? SIGNUP_TITLE : LOGIN_TITLE }}
                </h3>
                <p class="text-base text-gray-300 leading-relaxed mb-6" style="font-weight: 200;">
                  {{ isSignUp ? SIGNUP_DESCRIPTION : LOGIN_DESCRIPTION }}
                </p>
                
                <form @submit.prevent="handleSubmit" class="space-y-4">
                  <div class="space-y-2">
                    <label for="email" class="text-sm text-gray-300" style="font-weight: 300;">
                      Email
                    </label>
                    <input
                      id="email"
                      v-model="formData.email"
                      type="email"
                      placeholder="inserisci la tua email"
                      required
                      class="w-full px-3 py-2 bg-gray-800 border border-gray-700 text-white placeholder-gray-500 rounded-lg focus:border-green-400 focus:ring-1 focus:ring-green-400 focus:outline-none transition-colors"
                    />
                  </div>
                  
                  <div class="space-y-2">
                    <label for="password" class="text-sm text-gray-300" style="font-weight: 300;">
                      Password
                    </label>
                    <div class="relative">
                      <input
                        id="password"
                        v-model="formData.password"
                        :type="showPassword ? 'text' : 'password'"
                        :placeholder="isSignUp ? 'crea una password sicura' : 'inserisci la tua password'"
                        required
                        class="w-full px-3 py-2 bg-gray-800 border border-gray-700 text-white placeholder-gray-500 rounded-lg focus:border-green-400 focus:ring-1 focus:ring-green-400 focus:outline-none transition-colors pr-10"
                      />
                      <button
                        type="button"
                        @click="showPassword = !showPassword"
                        class="absolute right-0 top-0 h-full px-3 py-2 hover:bg-gray-700 rounded-r-lg transition-colors"
                      >
                        <Eye v-if="!showPassword" class="h-4 w-4 text-gray-400" />
                        <EyeOff v-else class="h-4 w-4 text-gray-400" />
                      </button>
                    </div>
                  </div>
                  
                  <button 
                    type="submit" 
                    class="w-full bg-green-600 hover:bg-green-700 text-white rounded-lg shadow-lg py-2 px-4 transition-all duration-200 flex items-center justify-center gap-2"
                    :disabled="authStore.isLoading"
                    :class="{ 'opacity-50 cursor-not-allowed': authStore.isLoading }"
                  >
                    <Loader2 v-if="authStore.isLoading" class="h-4 w-4 animate-spin" />
                    <span>
                      {{ authStore.isLoading 
                        ? (isSignUp ? 'Creazione account...' : 'Accesso in corso...') 
                        : (isSignUp ? 'Crea Account' : 'Accedi') 
                      }}
                    </span>
                  </button>
                </form>
                
                <div class="flex flex-col space-y-4 mt-6">
                  <div class="text-center">
                    <span class="text-sm text-gray-400" style="font-weight: 200;">
                      {{ isSignUp ? 'Hai già un account?' : 'Non hai un account?' }}
                    </span>
                    <button
                      @click="toggleMode"
                      class="p-0 ml-1 text-green-400 hover:text-green-300 transition-colors"
                    >
                      {{ isSignUp ? 'Accedi' : 'Registrati' }}
                    </button>
                  </div>
                  
                  <div v-if="isSignUp">
                    <p class="text-xs text-gray-500 text-center" style="font-weight: 200;">
                      Registrandoti accetti i nostri 
                      <a href="#" class="text-green-400 hover:text-green-300">termini di servizio</a>
                      e la
                      <a href="#" class="text-green-400 hover:text-green-300">privacy policy</a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <!-- Back to Top Button -->
    <button 
      v-if="showBackToTop"
      @click="scrollToTop"
      class="fixed bottom-8 right-8 bg-green-600 hover:bg-green-700 text-white p-3 rounded-full shadow-lg transition-all duration-300 z-50"
    >
      <ArrowUp class="h-5 w-5" />
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import { useRouter } from 'vue-router'
import { Eye, EyeOff, Loader2, ArrowUp } from 'lucide-vue-next'
import { useAuthStore } from '../stores/auth'
import { useUIStore } from '../stores/ui'

// Constants - same as new loginPage design
const LOGIN_TITLE = "Bentornato"
const LOGIN_DESCRIPTION = "Accedi per gestire i tuoi Ai Agent."
const SIGNUP_TITLE = "Crea un Account"
const SIGNUP_DESCRIPTION = "Registrati per iniziare a trasformare la tua azienda con PilotPro."
const BRAND_TITLE = "I primi Ai business Agent in Italia"
const BRAND_DESCRIPTION = "Trasformiamo il modo di lavorare delle aziende attraverso l'intelligenza artificiale. Benvenuto!"

// Stores - Pinia composition pattern like n8n
const authStore = useAuthStore()
const uiStore = useUIStore()
const router = useRouter()

// Local state
const isSignUp = ref(false)
const showPassword = ref(false)
const showBackToTop = ref(false)

const formData = ref({
  email: '',
  password: '',
})

// Methods
const toggleMode = () => {
  isSignUp.value = !isSignUp.value
  formData.value.email = ''
  formData.value.password = ''
}

const handleSubmit = async () => {
  try {
    if (isSignUp.value) {
      // For signup, redirect to demo booking
      window.location.href = '/prenota-demo'
    } else {
      // Login with any credentials
      await authStore.login(formData.value.email, formData.value.password)
      uiStore.showToast('Login', 'Accesso effettuato con successo!', 'success')
      router.push('/dashboard')
    }
  } catch (error: any) {
    uiStore.showToast('Errore', error.message || 'Credenziali non valide', 'error')
  }
}

const scrollToTop = () => {
  window.scrollTo({ top: 0, behavior: 'smooth' })
}

// Lifecycle - Vue 3 composition API
onMounted(() => {
  // Handle back to top button
  const handleScroll = () => {
    showBackToTop.value = window.scrollY > 400
  }
  
  window.addEventListener('scroll', handleScroll)
  
  // Cleanup
  onUnmounted(() => {
    window.removeEventListener('scroll', handleScroll)
  })
})
</script>

<style scoped>
/* Component-specific styles */
.animate-float {
  animation: float 6s ease-in-out infinite;
}

@keyframes float {
  0%, 100% { transform: translateY(0px); }
  50% { transform: translateY(-20px); }
}
</style>
